# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-04-19T03:16:33+00:00

from __future__ import annotations

from typing import Optional, Literal

from pydantic import AnyUrl, BaseModel, Field
from dat_core.pydantic_models import ConnectionSpecification

class ConnectionSpecificationModel(ConnectionSpecification):
    cohere_api_key: str = Field(..., description='Cohere key', title='Cohere API key')
    cohere_model: Optional[str] = Field(
        'embed-english-v3.0', description='Cohere model', title='Cohere model'
    )

class CohereSpecification(BaseModel):
    documentation_url: Optional[AnyUrl] = None
    name: Literal['Cohere']
    module_name: Literal['cohere']
    
    connection_specification: ConnectionSpecificationModel = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
