# generated by datamodel-codegen:
#   filename:  specs.yml
#   timestamp: 2024-05-16T09:52:11+00:00

from __future__ import annotations

from typing import Optional, Literal

from pydantic import BaseModel, Field
from dat_core.pydantic_models import ConnectionSpecification


class ConnectionSpecificationModel(ConnectionSpecification):
    openai_api_key: str = Field(..., description='OpenAI API key',
                                title='OpenAI API key', json_schema_extra={
                                    'ui-opts': {
                                        'masked': True,
                                    }
                                })
    openai_model: Optional[str] = Field(
        'text-embedding-ada-002', description='OpenAI model', title='OpenAI model'
    )


class OpenAISpecification(BaseModel):
    name: Literal['OpenAI']
    module_name: Literal['openai']
    documentation_url: Optional[str] = (
        'https://datlabs.gitbook.io/datlabs/integrations/generators/openai'
    )

    connection_specification: ConnectionSpecificationModel = Field(
        ...,
        description='ConnectorDefinition specific blob. Must be a valid JSON string.',
    )
